# WhatATheme
markdown: kramdown

# URL of the Site
url: http://blog.bouldermon.com
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Blogmon
# Description of the Site
description: 볼더몬스터 이야기
#description: 볼더몬스터 블로그
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: climbing, bouldering, blog
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/blogmon_main.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: cps1990@naver.com
#facebook_username: thedevslot
#twitter_username: thedevslot
instagram_username: pilseong_c
#linkedin_username: thedevslot
#github_username:  yourbran
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: Pilseong
# URL for the Image of the Author
author-image: /assets/images/author_profile.jpg
# 60 Words About the Author
author-about: 함께 볼더링을 즐기며 그 과정 속에서 일어나는 이야기를 기록합니다. 힘내라 볼더몬스터! 함께해요 볼더링!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/yourbran

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page
  -
    scope:
      path: 'projects'
      type: 'posts'
    values:
      layout: post

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
